#!/usr/bin/env bash
set -euo pipefail

# GATE_2: Check E2E build authorization before proceeding
ROOT="$(git rev-parse --show-toplevel 2>/dev/null || pwd)"
bash "$ROOT/scripts/e2e/require-e2e-build-authorization.sh" || exit 1

REPORTS="$ROOT/reports/e2e-desktop"
LOG="$REPORTS/dev_tauri.log"
TAURI_DRIVER_LOG="$REPORTS/tauri_driver.log"
WDIO_LOG="$REPORTS/wdio.log"
BOOT_SMOKE="$REPORTS/BOOT_DESKTOP_SMOKE.md"
STEP5="$REPORTS/UNBLOCK_STEP_5_RUNNER_UPDATE.md"
MODE_FILE="$REPORTS/DESKTOP_E2E_MODE.json"
BLOCKED_REPORT="$REPORTS/DESKTOP_E2E_BLOCKED.md"

mkdir -p "$REPORTS"
: > "$LOG"
: > "$TAURI_DRIVER_LOG"
: > "$WDIO_LOG"
if [[ ! -f "$STEP5" ]]; then
  cat > "$STEP5" <<'EOF'
# UNBLOCK_STEP_5_RUNNER_UPDATE — Desktop E2E

Run: PENDING
Status: PENDING
EOF
fi
if [[ ! -f "$BOOT_SMOKE" ]]; then
  cat > "$BOOT_SMOKE" <<'EOF'
# BOOT_DESKTOP_SMOKE — Desktop E2E

Status: PENDING
Notes: Generated by e2e:desktop harness.
EOF
fi
if [[ ! -f "$BLOCKED_REPORT" ]]; then
  cat > "$BLOCKED_REPORT" <<'EOF'
# DESKTOP_E2E_BLOCKED — Desktop E2E

Status: PENDING
Notes: Generated by e2e:desktop harness.
EOF
fi

cleanup() {
  if [[ -n "${TAURI_PID:-}" ]]; then
    kill "$TAURI_PID" 2>/dev/null || true
  fi
  if [[ -n "${DRIVER_PID:-}" ]]; then
    kill "$DRIVER_PID" 2>/dev/null || true
  fi
}
trap cleanup EXIT

port_in_use() {
  local port="$1"
  ss -ltn 2>/dev/null | awk '{print $4}' | grep -q ":${port}$"
}

pick_driver_port() {
  for port in 4444 4445 4446 4447 4448 4449 4450; do
    if ! port_in_use "$port"; then
      echo "$port"
      return 0
    fi
  done
  return 1
}

wait_for_driver() {
  local port="$1"
  local timeout="${2:-20}"
  local start
  start=$(date +%s)
  while [[ $(( $(date +%s) - start )) -lt $timeout ]]; do
    if command -v curl >/dev/null 2>&1; then
      if curl -fsS "http://127.0.0.1:${port}/status" >/dev/null 2>&1; then
        return 0
      fi
    fi
    sleep 1
  done
  return 1
}

stop_stray_driver() {
  if command -v pgrep >/dev/null 2>&1 && pgrep -f "tauri-driver" >/dev/null 2>&1; then
    echo "[e2e:desktop] WARN: stopping stray tauri-driver processes"
    pkill -f "tauri-driver" || true
    sleep 1
  fi
}

if [[ ! -f "$MODE_FILE" ]]; then
  bash "$ROOT"/scripts/e2e/ensure-linux-desktop-driver.sh >/dev/null
fi

if [[ ! -f "$MODE_FILE" ]]; then
  echo "[e2e:desktop] ERROR: mode file missing ($MODE_FILE)" | tee -a "$STEP5"
  exit 1
fi

MODE=$(node -e "const fs=require('fs');const p='${MODE_FILE}';const data=JSON.parse(fs.readFileSync(p,'utf-8'));console.log(data.mode || 'BLOCKED');")
TAURI_DRIVER_PATH=$(node -e "const fs=require('fs');const p='${MODE_FILE}';const data=JSON.parse(fs.readFileSync(p,'utf-8'));console.log(data.tauri_driver_path || '');")
NATIVE_DRIVER_STATUS=$(node -e "const fs=require('fs');const p='${MODE_FILE}';const data=JSON.parse(fs.readFileSync(p,'utf-8'));console.log(data.native_driver || 'MISSING');")

if [[ "$MODE" == "BLOCKED" ]]; then
  cat >> "$BLOCKED_REPORT" <<EOF

---

Run: $(date -Iseconds)
Status: BLOCKED
Reason: tauri-driver missing
Mode: $MODE
Native driver: $NATIVE_DRIVER_STATUS
Mode file: $MODE_FILE
EOF
  cat >> "$BOOT_SMOKE" <<EOF

---

Run: $(date -Iseconds)
Status: BLOCKED
Reason: tauri-driver missing
Mode: $MODE
EOF
  exit 1
fi

echo "[e2e:desktop] Launching dev:tauri (logs: $LOG)"
if command -v pnpm >/dev/null 2>&1; then
  (pnpm run dev:tauri 2>&1 | tee "$LOG") &
else
  ("$ROOT"/node_modules/.bin/pnpm run dev:tauri 2>&1 | tee "$LOG") &
fi
TAURI_PID=$!

READY_TIMEOUT=120
READY_MARKERS=("frontend.boot" "Main window shown successfully" "VITE")

start_ts=$(date +%s)
ready=false
while [[ $(( $(date +%s) - start_ts )) -lt $READY_TIMEOUT ]]; do
  for marker in "${READY_MARKERS[@]}"; do
    if grep -q "$marker" "$LOG"; then
      ready=true
      break
    fi
  done
  if [[ "$ready" == "true" ]]; then
    break
  fi
  sleep 2
 done

if [[ "$ready" != "true" ]]; then
  echo "[e2e:desktop] ERROR: dev:tauri not ready (timeout ${READY_TIMEOUT}s)" | tee -a "$LOG"
  cat >> "$BOOT_SMOKE" <<EOF

---

Run: $(date -Iseconds)
Status: FAIL
Reason: dev:tauri not ready within ${READY_TIMEOUT}s
EOF
  exit 1
fi

cat >> "$BOOT_SMOKE" <<EOF

---

Run: $(date -Iseconds)
Status: READY
Mode: $MODE
Markers: ${READY_MARKERS[*]}
EOF

if [[ "$MODE" == "AUTO_UI_FULL" ]]; then
  if [[ -z "$TAURI_DRIVER_PATH" ]]; then
    echo "[e2e:desktop] ERROR: tauri-driver path missing (mode FULL)" | tee -a "$STEP5"
    exit 1
  fi
  stop_stray_driver
  DRIVER_PORT=""
  if DRIVER_PORT=$(pick_driver_port); then
    :
  else
    cat >> "$BLOCKED_REPORT" <<EOF

---

Run: $(date -Iseconds)
Status: BLOCKED
Reason: No free tauri-driver port available (4444-4450)
Mode: $MODE
EOF
    exit 1
  fi

  echo "[e2e:desktop] Starting tauri-driver (port ${DRIVER_PORT})"
  "$TAURI_DRIVER_PATH" --port "$DRIVER_PORT" 2>&1 | tee "$TAURI_DRIVER_LOG" &
  DRIVER_PID=$!

  if ! wait_for_driver "$DRIVER_PORT" 20; then
    cat >> "$BLOCKED_REPORT" <<EOF

---

Run: $(date -Iseconds)
Status: BLOCKED
Reason: tauri-driver failed to start on port ${DRIVER_PORT}
Mode: $MODE
EOF
    exit 1
  fi

  echo "[e2e:desktop] Running WebdriverIO"
  AUTO_UI_MODE="AUTO_UI_FULL" AUTO_UI_COVERAGE="FULL" AUTO_UI_CERTIFIABLE="YES" TAURI_DRIVER_PORT="${DRIVER_PORT}" WDIO_PORT="${DRIVER_PORT}" \
    "$ROOT"/node_modules/.bin/wdio run "$ROOT/wdio.desktop.conf.cjs" 2>&1 | tee "$WDIO_LOG"
else
  echo "[e2e:desktop] MODE LIMITED: skipping WDIO, running AI core fallback"
  AUTO_UI_MODE="AUTO_UI_LIMITED" AUTO_UI_COVERAGE="PARTIAL" AUTO_UI_CERTIFIABLE="NO" \
    node "$ROOT"/e2e/desktop/ai-verification.limited.e2e.js 2>&1 | tee "$WDIO_LOG"
fi

cat >> "$STEP5" <<EOF

---

Run: $(date -Iseconds)
Status: DONE
tauri-driver: $TAURI_DRIVER_PATH
logs: dev_tauri.log, tauri_driver.log, wdio.log
EOF
