#!/bin/bash
# fix_main_rs_manual.sh - Guide réparation manuelle main.rs

echo "🔧 TITANE∞ - Réparation manuelle main.rs"
echo ""
echo "Le fichier src-tauri/src/main.rs a des accolades manquantes."
echo "Voici les corrections à appliquer manuellement :"
echo ""

echo "═══════════════════════════════════════════════════════════════"
echo "OPTION 1 : Ouvrir dans VS Code et utiliser rust-analyzer"
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "1. Ouvrir le fichier :"
echo "   code src-tauri/src/main.rs"
echo ""
echo "2. Dans VS Code :"
echo "   - Shift+Alt+F (Format Document)"
echo "   - Problems panel → Clic droit → Quick Fix"
echo "   - Ou utiliser commande palette : 'Rust Analyzer: Fix all'"
echo ""

echo "═══════════════════════════════════════════════════════════════"
echo "OPTION 2 : Restaurer depuis template Tauri propre"
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "# Créer projet temporaire avec template propre"
echo "cd /tmp"
echo "npx create-tauri-app@latest temp-titane --template vanilla"
echo "cd temp-titane"
echo ""
echo "# Copier le main.rs template"
echo "cp src-tauri/src/main.rs ~/BACKUP_main_propre.rs"
echo ""
echo "# Retour projet TITANE et adapter"
echo "cd ~/Documents/TITANE_NEWGEN/TITANE_INFINITY/src-tauri/src"
echo "# Copier structure de base et réintégrer vos modules"
echo ""

echo "═══════════════════════════════════════════════════════════════"
echo "OPTION 3 : Corrections manuelles ligne par ligne"
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "Ouvrir : nano src-tauri/src/main.rs"
echo ""
echo "Corrections à appliquer :"
echo ""
echo "1. Ligne ~395 - Après 'log::error Resonance tick failed'"
echo "   Ajouter :  }"
echo "   Puis : } else {"
echo ""
echo "2. Ligne ~402 - Après 'memory.lock()'"
echo "   Ajouter : ) au bout de la ligne"
echo ""
echo "3. Ligne ~410 - Après 'log::error dependencies for Cortex'"
echo "   Ajouter :    }"
echo ""
echo "4. Ligne ~412 - Après 'log::error Failed to lock Cortex'"
echo "   Ajouter : }"
echo ""
echo "5. Ligne ~490 - Après le nombre '20'"
echo "   Remplacer par : 20"
echo "   Puis ligne suivante : ) {"
echo ""
echo "6. Ligne ~495 - Après 'log::error Continuum snapshot'"
echo "   Ajouter :        }"
echo ""
echo "7. Ligne ~500 - Après 'log::error dependencies for Continuum'"
echo "   Ajouter :    }"
echo "            }"
echo "        } else {"
echo ""

echo "═══════════════════════════════════════════════════════════════"
echo "OPTION 4 : Utiliser rustfmt avec fix"
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "cd src-tauri"
echo "cargo fix --allow-dirty 2>&1 | tee fix.log"
echo "rustfmt --edition 2021 src/main.rs"
echo ""

echo "═══════════════════════════════════════════════════════════════"
echo "VÉRIFICATION après correction"
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "cd src-tauri"
echo "cargo check --message-format=short"
echo ""
echo "Si erreurs persistent, consulter :"
echo "  - RAPPORT_AUTO_FIX_PHASE_8_BLOCAGE.md"
echo "  - SOLUTION_BUILD_DOCKER.md"
echo ""
echo "✅ Guide terminé"
