// ═══════════════════════════════════════════════════════════════════════════
// TITANE∞ v19.2Ω — AUTOMATIONS MODULE (Rust)
// ═══════════════════════════════════════════════════════════════════════════
// Système d'automations avec validation, sécurité et exécution contrôlée
// ═══════════════════════════════════════════════════════════════════════════

use serde::{Deserialize, Serialize};
use std::collections::{HashMap, HashSet};
use std::sync::{Arc, Mutex};
use std::time::{SystemTime, UNIX_EPOCH};
use tauri::State;

use crate::core::tapi_error::TAPIError;

// ─────────────────────────────────────────────────────────────────────────────
// TYPES FONDAMENTAUX
// ─────────────────────────────────────────────────────────────────────────────

/// Identifiants d'automations (synchronisé avec TypeScript)
#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum AutomationId {
    AutoBackup,
    AutoCleanup,
    AutoAudit,
    AutoFormat,
    AutoTestRun,
    AutoTypeCheck,
    AutoGitStatus,
    AutoGitCommit,
    AutoGenerateDoc,
    AutoSummarizeChat,
    AutoExportConversation,
    AutoMemoryCompact,
    AutoXpSync,
    AutoHealthCheck,
    AutoProjectAnalysis,
    AutoDependencyCheck,
}

impl AutomationId {
    /// Parse depuis string (safe)
    pub fn from_str(s: &str) -> Option<Self> {
        match s.to_lowercase().as_str() {
            "auto_backup" => Some(AutomationId::AutoBackup),
            "auto_cleanup" => Some(AutomationId::AutoCleanup),
            "auto_audit" => Some(AutomationId::AutoAudit),
            "auto_format" => Some(AutomationId::AutoFormat),
            "auto_test_run" => Some(AutomationId::AutoTestRun),
            "auto_type_check" => Some(AutomationId::AutoTypeCheck),
            "auto_git_status" => Some(AutomationId::AutoGitStatus),
            "auto_git_commit" => Some(AutomationId::AutoGitCommit),
            "auto_generate_doc" => Some(AutomationId::AutoGenerateDoc),
            "auto_summarize_chat" => Some(AutomationId::AutoSummarizeChat),
            "auto_export_conversation" => Some(AutomationId::AutoExportConversation),
            "auto_memory_compact" => Some(AutomationId::AutoMemoryCompact),
            "auto_xp_sync" => Some(AutomationId::AutoXpSync),
            "auto_health_check" => Some(AutomationId::AutoHealthCheck),
            "auto_project_analysis" => Some(AutomationId::AutoProjectAnalysis),
            "auto_dependency_check" => Some(AutomationId::AutoDependencyCheck),
            _ => None,
        }
    }

    /// Convertit en string
    pub fn as_str(&self) -> &'static str {
        match self {
            AutomationId::AutoBackup => "auto_backup",
            AutomationId::AutoCleanup => "auto_cleanup",
            AutomationId::AutoAudit => "auto_audit",
            AutomationId::AutoFormat => "auto_format",
            AutomationId::AutoTestRun => "auto_test_run",
            AutomationId::AutoTypeCheck => "auto_type_check",
            AutomationId::AutoGitStatus => "auto_git_status",
            AutomationId::AutoGitCommit => "auto_git_commit",
            AutomationId::AutoGenerateDoc => "auto_generate_doc",
            AutomationId::AutoSummarizeChat => "auto_summarize_chat",
            AutomationId::AutoExportConversation => "auto_export_conversation",
            AutomationId::AutoMemoryCompact => "auto_memory_compact",
            AutomationId::AutoXpSync => "auto_xp_sync",
            AutomationId::AutoHealthCheck => "auto_health_check",
            AutomationId::AutoProjectAnalysis => "auto_project_analysis",
            AutomationId::AutoDependencyCheck => "auto_dependency_check",
        }
    }
}

/// Catégories d'automations
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum AutomationCategory {
    Maintenance,
    CodeQuality,
    Testing,
    Git,
    Documentation,
    Memory,
    Analytics,
    System,
}

/// Niveau de sécurité
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum SecurityLevel {
    Safe = 0,
    Moderate = 1,
    Elevated = 2,
    Critical = 3,
}

impl SecurityLevel {
    pub fn from_u8(v: u8) -> Option<Self> {
        match v {
            0 => Some(SecurityLevel::Safe),
            1 => Some(SecurityLevel::Moderate),
            2 => Some(SecurityLevel::Elevated),
            3 => Some(SecurityLevel::Critical),
            _ => None,
        }
    }
}

/// Statut d'exécution
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum ExecutionStatus {
    Pending,
    Running,
    Success,
    Failed,
    Cancelled,
    RequiresConfirmation,
}

// ─────────────────────────────────────────────────────────────────────────────
// STRUCTURES DE DONNÉES
// ─────────────────────────────────────────────────────────────────────────────

/// Configuration d'une automation (version Rust simplifiée)
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AutomationConfig {
    pub id: String,
    pub name: String,
    pub category: AutomationCategory,
    pub security_level: SecurityLevel,
    pub required_permission: u8,
    pub allowed_modes: Option<Vec<String>>,
    pub base_xp_reward: u32,
    pub requires_confirmation: bool,
    pub timeout_ms: u64,
    pub cooldown_ms: u64,
}

/// Requête d'exécution d'automation
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AutomationRequest {
    pub automation_id: String,
    pub parameters: HashMap<String, serde_json::Value>,
    pub mode_id: String,
    pub permission_level: u8,
    pub triggered_by: String, // "user" | "system" | "schedule" | "chain"
    pub user_confirmed: bool,
}

/// Résultat d'exécution
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AutomationResult {
    pub execution_id: String,
    pub automation_id: String,
    pub status: ExecutionStatus,
    pub started_at: u64,
    pub completed_at: Option<u64>,
    pub duration_ms: Option<u64>,
    pub output: Option<serde_json::Value>,
    pub error: Option<String>,
    pub logs: Vec<AutomationLog>,
    pub xp_awarded: u32,
}

/// Log d'exécution
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AutomationLog {
    pub timestamp: u64,
    pub level: String, // "info" | "warn" | "error" | "debug"
    pub message: String,
}

/// Statistiques d'automations
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AutomationStats {
    pub total_executions: u64,
    pub successful_executions: u64,
    pub failed_executions: u64,
    pub total_xp_awarded: u64,
    pub executions_by_category: HashMap<String, u64>,
    pub average_duration_ms: u64,
}

// ─────────────────────────────────────────────────────────────────────────────
// STATE
// ─────────────────────────────────────────────────────────────────────────────

/// État du système d'automations
pub struct AutomationEngineState {
    /// Configurations des automations
    configs: Arc<Mutex<HashMap<String, AutomationConfig>>>,
    /// Historique des exécutions (limité à 100)
    history: Arc<Mutex<Vec<AutomationResult>>>,
    /// Cooldowns actifs (automation_id -> timestamp fin)
    cooldowns: Arc<Mutex<HashMap<String, u64>>>,
    /// Statistiques
    stats: Arc<Mutex<AutomationStats>>,
    /// Exécutions en cours
    running: Arc<Mutex<HashSet<String>>>,
}

// ─────────────────────────────────────────────────────────────────────────────
// INITIALISATION
// ─────────────────────────────────────────────────────────────────────────────

pub fn init() -> AutomationEngineState {
    let mut configs = HashMap::new();

    // Enregistrer toutes les automations
    register_automations(&mut configs);

    let state = AutomationEngineState {
        configs: Arc::new(Mutex::new(configs)),
        history: Arc::new(Mutex::new(Vec::new())),
        cooldowns: Arc::new(Mutex::new(HashMap::new())),
        stats: Arc::new(Mutex::new(AutomationStats {
            total_executions: 0,
            successful_executions: 0,
            failed_executions: 0,
            total_xp_awarded: 0,
            executions_by_category: HashMap::new(),
            average_duration_ms: 0,
        })),
        running: Arc::new(Mutex::new(HashSet::new())),
    };

    // Phase 1 Stabilisation: Gérer lock poison
    let configs_len = match state.configs.lock() {
        Ok(c) => c.len(),
        Err(e) => {
            eprintln!("Warning: Automations configs lock poisoned in init, recovering: {}", e);
            e.into_inner().len()
        }
    };
    println!("[AUTOMATION] Engine initialized with {} automations", configs_len);

    state
}

fn register_automations(configs: &mut HashMap<String, AutomationConfig>) {
    // Maintenance
    configs.insert("auto_backup".to_string(), AutomationConfig {
        id: "auto_backup".to_string(),
        name: "Sauvegarde Automatique".to_string(),
        category: AutomationCategory::Maintenance,
        security_level: SecurityLevel::Moderate,
        required_permission: 2,
        allowed_modes: Some(vec!["dev".to_string(), "admin".to_string()]),
        base_xp_reward: 25,
        requires_confirmation: true,
        timeout_ms: 300000,
        cooldown_ms: 60000,
    });

    configs.insert("auto_cleanup".to_string(), AutomationConfig {
        id: "auto_cleanup".to_string(),
        name: "Nettoyage Projet".to_string(),
        category: AutomationCategory::Maintenance,
        security_level: SecurityLevel::Moderate,
        required_permission: 2,
        allowed_modes: Some(vec!["dev".to_string(), "admin".to_string()]),
        base_xp_reward: 15,
        requires_confirmation: true,
        timeout_ms: 60000,
        cooldown_ms: 30000,
    });

    configs.insert("auto_audit".to_string(), AutomationConfig {
        id: "auto_audit".to_string(),
        name: "Audit Automatique".to_string(),
        category: AutomationCategory::Analytics,
        security_level: SecurityLevel::Safe,
        required_permission: 1,
        allowed_modes: Some(vec!["audit".to_string(), "dev".to_string(), "admin".to_string(), "strategy".to_string()]),
        base_xp_reward: 50,
        requires_confirmation: false,
        timeout_ms: 600000,
        cooldown_ms: 120000,
    });

    // Code Quality
    configs.insert("auto_format".to_string(), AutomationConfig {
        id: "auto_format".to_string(),
        name: "Formatage Code".to_string(),
        category: AutomationCategory::CodeQuality,
        security_level: SecurityLevel::Moderate,
        required_permission: 2,
        allowed_modes: Some(vec!["dev".to_string(), "admin".to_string()]),
        base_xp_reward: 10,
        requires_confirmation: false,
        timeout_ms: 60000,
        cooldown_ms: 10000,
    });

    configs.insert("auto_type_check".to_string(), AutomationConfig {
        id: "auto_type_check".to_string(),
        name: "Vérification Types".to_string(),
        category: AutomationCategory::CodeQuality,
        security_level: SecurityLevel::Safe,
        required_permission: 1,
        allowed_modes: Some(vec!["dev".to_string(), "admin".to_string(), "audit".to_string()]),
        base_xp_reward: 20,
        requires_confirmation: false,
        timeout_ms: 180000,
        cooldown_ms: 30000,
    });

    // Testing
    configs.insert("auto_test_run".to_string(), AutomationConfig {
        id: "auto_test_run".to_string(),
        name: "Lancer Tests".to_string(),
        category: AutomationCategory::Testing,
        security_level: SecurityLevel::Safe,
        required_permission: 1,
        allowed_modes: Some(vec!["dev".to_string(), "admin".to_string(), "audit".to_string()]),
        base_xp_reward: 30,
        requires_confirmation: false,
        timeout_ms: 600000,
        cooldown_ms: 60000,
    });

    // Git
    configs.insert("auto_git_status".to_string(), AutomationConfig {
        id: "auto_git_status".to_string(),
        name: "Git Status".to_string(),
        category: AutomationCategory::Git,
        security_level: SecurityLevel::Safe,
        required_permission: 0,
        allowed_modes: None, // Tous les modes
        base_xp_reward: 5,
        requires_confirmation: false,
        timeout_ms: 10000,
        cooldown_ms: 5000,
    });

    configs.insert("auto_git_commit".to_string(), AutomationConfig {
        id: "auto_git_commit".to_string(),
        name: "Git Commit Assisté".to_string(),
        category: AutomationCategory::Git,
        security_level: SecurityLevel::Moderate,
        required_permission: 2,
        allowed_modes: Some(vec!["dev".to_string(), "admin".to_string()]),
        base_xp_reward: 20,
        requires_confirmation: true,
        timeout_ms: 30000,
        cooldown_ms: 10000,
    });

    // Documentation
    configs.insert("auto_generate_doc".to_string(), AutomationConfig {
        id: "auto_generate_doc".to_string(),
        name: "Générer Documentation".to_string(),
        category: AutomationCategory::Documentation,
        security_level: SecurityLevel::Moderate,
        required_permission: 2,
        allowed_modes: Some(vec!["dev".to_string(), "admin".to_string(), "synthesis".to_string()]),
        base_xp_reward: 35,
        requires_confirmation: false,
        timeout_ms: 300000,
        cooldown_ms: 60000,
    });

    // Memory
    configs.insert("auto_summarize_chat".to_string(), AutomationConfig {
        id: "auto_summarize_chat".to_string(),
        name: "Résumer Conversation".to_string(),
        category: AutomationCategory::Memory,
        security_level: SecurityLevel::Safe,
        required_permission: 0,
        allowed_modes: None,
        base_xp_reward: 15,
        requires_confirmation: false,
        timeout_ms: 30000,
        cooldown_ms: 10000,
    });

    configs.insert("auto_export_conversation".to_string(), AutomationConfig {
        id: "auto_export_conversation".to_string(),
        name: "Exporter Conversation".to_string(),
        category: AutomationCategory::Memory,
        security_level: SecurityLevel::Safe,
        required_permission: 1,
        allowed_modes: None,
        base_xp_reward: 10,
        requires_confirmation: false,
        timeout_ms: 10000,
        cooldown_ms: 5000,
    });

    configs.insert("auto_memory_compact".to_string(), AutomationConfig {
        id: "auto_memory_compact".to_string(),
        name: "Compacter Mémoire".to_string(),
        category: AutomationCategory::Memory,
        security_level: SecurityLevel::Moderate,
        required_permission: 2,
        allowed_modes: Some(vec!["admin".to_string(), "dev".to_string()]),
        base_xp_reward: 20,
        requires_confirmation: true,
        timeout_ms: 60000,
        cooldown_ms: 300000,
    });

    // System
    configs.insert("auto_xp_sync".to_string(), AutomationConfig {
        id: "auto_xp_sync".to_string(),
        name: "Synchroniser XP".to_string(),
        category: AutomationCategory::System,
        security_level: SecurityLevel::Safe,
        required_permission: 0,
        allowed_modes: None,
        base_xp_reward: 5,
        requires_confirmation: false,
        timeout_ms: 10000,
        cooldown_ms: 30000,
    });

    configs.insert("auto_health_check".to_string(), AutomationConfig {
        id: "auto_health_check".to_string(),
        name: "Vérification Santé".to_string(),
        category: AutomationCategory::System,
        security_level: SecurityLevel::Safe,
        required_permission: 0,
        allowed_modes: None,
        base_xp_reward: 10,
        requires_confirmation: false,
        timeout_ms: 30000,
        cooldown_ms: 60000,
    });

    configs.insert("auto_project_analysis".to_string(), AutomationConfig {
        id: "auto_project_analysis".to_string(),
        name: "Analyse Projet".to_string(),
        category: AutomationCategory::Analytics,
        security_level: SecurityLevel::Safe,
        required_permission: 1,
        allowed_modes: Some(vec!["dev".to_string(), "admin".to_string(), "audit".to_string(), "strategy".to_string()]),
        base_xp_reward: 40,
        requires_confirmation: false,
        timeout_ms: 300000,
        cooldown_ms: 120000,
    });

    configs.insert("auto_dependency_check".to_string(), AutomationConfig {
        id: "auto_dependency_check".to_string(),
        name: "Vérifier Dépendances".to_string(),
        category: AutomationCategory::Analytics,
        security_level: SecurityLevel::Safe,
        required_permission: 1,
        allowed_modes: Some(vec!["dev".to_string(), "admin".to_string(), "audit".to_string()]),
        base_xp_reward: 25,
        requires_confirmation: false,
        timeout_ms: 120000,
        cooldown_ms: 300000,
    });
}

// ─────────────────────────────────────────────────────────────────────────────
// HELPERS
// ─────────────────────────────────────────────────────────────────────────────

fn get_timestamp() -> u64 {
    SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .unwrap_or_default()
        .as_millis() as u64
}

fn generate_execution_id() -> String {
    format!("exec_{}_{}", get_timestamp(), rand::random::<u32>())
}

// ─────────────────────────────────────────────────────────────────────────────
// VALIDATION
// ─────────────────────────────────────────────────────────────────────────────

/// Valider qu'une automation peut être exécutée
fn validate_automation_request(
    config: &AutomationConfig,
    request: &AutomationRequest,
    cooldowns: &HashMap<String, u64>,
    running: &HashSet<String>,
) -> Result<(), String> {
    let now = get_timestamp();

    // Vérifier si déjà en cours
    if running.contains(&request.automation_id) {
        return Err(format!("Automation '{}' déjà en cours d'exécution", config.name));
    }

    // Vérifier cooldown
    if let Some(cooldown_end) = cooldowns.get(&request.automation_id) {
        if *cooldown_end > now {
            let remaining = (*cooldown_end - now) / 1000;
            return Err(format!(
                "Automation '{}' en cooldown ({} secondes restantes)",
                config.name, remaining
            ));
        }
    }

    // Vérifier permission
    if request.permission_level < config.required_permission {
        return Err(format!(
            "Permission insuffisante pour '{}' (niveau {} requis, {} fourni)",
            config.name, config.required_permission, request.permission_level
        ));
    }

    // Vérifier mode autorisé
    if let Some(ref allowed_modes) = config.allowed_modes {
        if !allowed_modes.contains(&request.mode_id) {
            return Err(format!(
                "Mode '{}' non autorisé pour automation '{}'",
                request.mode_id, config.name
            ));
        }
    }

    // Vérifier confirmation si nécessaire
    if config.requires_confirmation && !request.user_confirmed {
        return Err(format!(
            "Automation '{}' nécessite une confirmation utilisateur",
            config.name
        ));
    }

    Ok(())
}

// ─────────────────────────────────────────────────────────────────────────────
// COMMANDES TAURI
// ─────────────────────────────────────────────────────────────────────────────

/// Obtenir la liste de toutes les automations
#[tauri::command]
pub fn automation_list(
    state: State<AutomationEngineState>,
) -> Result<Vec<AutomationConfig>, TAPIError> {
    let configs = state.configs.lock().map_err(|e| {
        TAPIError::internal(format!("Lock error: {}", e))
    })?;

    Ok(configs.values().cloned().collect())
}

/// Obtenir les automations disponibles pour un mode et niveau de permission
#[tauri::command]
pub fn automation_get_available(
    mode_id: String,
    permission_level: u8,
    state: State<AutomationEngineState>,
) -> Result<Vec<AutomationConfig>, TAPIError> {
    let configs = state.configs.lock().map_err(|e| {
        TAPIError::internal(format!("Lock error: {}", e))
    })?;

    let available: Vec<AutomationConfig> = configs
        .values()
        .filter(|config| {
            // Vérifier permission
            if permission_level < config.required_permission {
                return false;
            }

            // Vérifier mode
            if let Some(ref allowed_modes) = config.allowed_modes {
                if !allowed_modes.contains(&mode_id) {
                    return false;
                }
            }

            true
        })
        .cloned()
        .collect();

    Ok(available)
}

/// Valider une requête d'automation (sans exécuter)
#[tauri::command]
pub fn automation_validate(
    request: AutomationRequest,
    state: State<AutomationEngineState>,
) -> Result<bool, TAPIError> {
    let configs = state.configs.lock().map_err(|e| {
        TAPIError::internal(format!("Lock error: {}", e))
    })?;

    let config = configs.get(&request.automation_id).ok_or_else(|| {
        TAPIError::not_found(format!("Automation '{}' inconnue", request.automation_id))
    })?;

    let cooldowns = state.cooldowns.lock().map_err(|e| {
        TAPIError::internal(format!("Lock error: {}", e))
    })?;

    let running = state.running.lock().map_err(|e| {
        TAPIError::internal(format!("Lock error: {}", e))
    })?;

    match validate_automation_request(config, &request, &cooldowns, &running) {
        Ok(()) => Ok(true),
        Err(msg) => Err(TAPIError::validation(msg)),
    }
}

/// Exécuter une automation
#[tauri::command]
pub fn automation_execute(
    request: AutomationRequest,
    state: State<AutomationEngineState>,
) -> Result<AutomationResult, TAPIError> {
    let execution_id = generate_execution_id();
    let started_at = get_timestamp();

    // Récupérer la config
    let config = {
        let configs = state.configs.lock().map_err(|e| {
            TAPIError::internal(format!("Lock error: {}", e))
        })?;

        configs.get(&request.automation_id).ok_or_else(|| {
            TAPIError::not_found(format!("Automation '{}' inconnue", request.automation_id))
        })?.clone()
    };

    // Valider la requête
    {
        let cooldowns = state.cooldowns.lock().map_err(|e| {
            TAPIError::internal(format!("Lock error: {}", e))
        })?;

        let running = state.running.lock().map_err(|e| {
            TAPIError::internal(format!("Lock error: {}", e))
        })?;

        validate_automation_request(&config, &request, &cooldowns, &running)
            .map_err(|msg| TAPIError::validation(msg))?;
    }

    // Marquer comme en cours
    {
        let mut running = state.running.lock().map_err(|e| {
            TAPIError::internal(format!("Lock error: {}", e))
        })?;
        running.insert(request.automation_id.clone());
    }

    // Simuler l'exécution (dans une vraie implémentation, on exécuterait l'automation)
    let mut logs = Vec::new();
    logs.push(AutomationLog {
        timestamp: started_at,
        level: "info".to_string(),
        message: format!("Démarrage de '{}'", config.name),
    });

    // Simulation réussie
    let completed_at = get_timestamp();
    let duration_ms = completed_at - started_at;

    logs.push(AutomationLog {
        timestamp: completed_at,
        level: "info".to_string(),
        message: format!("'{}' terminée avec succès", config.name),
    });

    let xp_awarded = config.base_xp_reward;

    // Créer le résultat
    let result = AutomationResult {
        execution_id,
        automation_id: request.automation_id.clone(),
        status: ExecutionStatus::Success,
        started_at,
        completed_at: Some(completed_at),
        duration_ms: Some(duration_ms),
        output: Some(serde_json::json!({
            "message": format!("Automation '{}' exécutée avec succès", config.name)
        })),
        error: None,
        logs,
        xp_awarded,
    };

    // Retirer de "running"
    {
        let mut running = state.running.lock().map_err(|e| {
            TAPIError::internal(format!("Lock error: {}", e))
        })?;
        running.remove(&request.automation_id);
    }

    // Mettre à jour cooldown
    {
        let mut cooldowns = state.cooldowns.lock().map_err(|e| {
            TAPIError::internal(format!("Lock error: {}", e))
        })?;
        cooldowns.insert(request.automation_id.clone(), completed_at + config.cooldown_ms);
    }

    // Ajouter à l'historique
    {
        let mut history = state.history.lock().map_err(|e| {
            TAPIError::internal(format!("Lock error: {}", e))
        })?;
        history.push(result.clone());

        // Limiter à 100 entrées
        if history.len() > 100 {
            history.drain(0..(history.len() - 100));
        }
    }

    // Mettre à jour les stats
    {
        let mut stats = state.stats.lock().map_err(|e| {
            TAPIError::internal(format!("Lock error: {}", e))
        })?;

        stats.total_executions += 1;
        stats.successful_executions += 1;
        stats.total_xp_awarded += xp_awarded as u64;

        let category_key = format!("{:?}", config.category);
        *stats.executions_by_category.entry(category_key).or_insert(0) += 1;

        // Recalculer moyenne
        if stats.total_executions > 0 {
            stats.average_duration_ms = ((stats.average_duration_ms * (stats.total_executions - 1)) + duration_ms) / stats.total_executions;
        }
    }

    println!("[AUTOMATION] Exécuté: {} | XP: +{} | Durée: {}ms", config.name, xp_awarded, duration_ms);

    Ok(result)
}

/// Obtenir l'historique des exécutions
#[tauri::command]
pub fn automation_get_history(
    limit: Option<usize>,
    state: State<AutomationEngineState>,
) -> Result<Vec<AutomationResult>, TAPIError> {
    let history = state.history.lock().map_err(|e| {
        TAPIError::internal(format!("Lock error: {}", e))
    })?;

    let limit = limit.unwrap_or(20).min(100);
    let start = if history.len() > limit {
        history.len() - limit
    } else {
        0
    };

    Ok(history[start..].to_vec())
}

/// Obtenir les statistiques d'automations
#[tauri::command]
pub fn automation_get_stats(
    state: State<AutomationEngineState>,
) -> Result<AutomationStats, TAPIError> {
    let stats = state.stats.lock().map_err(|e| {
        TAPIError::internal(format!("Lock error: {}", e))
    })?;

    Ok(stats.clone())
}

/// Vérifier les cooldowns actifs
#[tauri::command]
pub fn automation_get_cooldowns(
    state: State<AutomationEngineState>,
) -> Result<HashMap<String, u64>, TAPIError> {
    let cooldowns = state.cooldowns.lock().map_err(|e| {
        TAPIError::internal(format!("Lock error: {}", e))
    })?;

    let now = get_timestamp();

    // Retourner seulement les cooldowns actifs (timestamp > now)
    let active: HashMap<String, u64> = cooldowns
        .iter()
        .filter(|(_, &end_time)| end_time > now)
        .map(|(id, &end_time)| (id.clone(), end_time - now))
        .collect();

    Ok(active)
}

/// Annuler une automation en cours (si cancellable)
#[tauri::command]
pub fn automation_cancel(
    automation_id: String,
    state: State<AutomationEngineState>,
) -> Result<bool, TAPIError> {
    let mut running = state.running.lock().map_err(|e| {
        TAPIError::internal(format!("Lock error: {}", e))
    })?;

    if running.remove(&automation_id) {
        println!("[AUTOMATION] Annulée: {}", automation_id);
        Ok(true)
    } else {
        Ok(false)
    }
}

// ─────────────────────────────────────────────────────────────────────────────
// TESTS
// ─────────────────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_automation_id_parsing() {
        assert_eq!(AutomationId::from_str("auto_backup"), Some(AutomationId::AutoBackup));
        assert_eq!(AutomationId::from_str("AUTO_TEST_RUN"), Some(AutomationId::AutoTestRun));
        assert_eq!(AutomationId::from_str("invalid"), None);
    }

    #[test]
    fn test_security_level_order() {
        assert!(SecurityLevel::Safe < SecurityLevel::Moderate);
        assert!(SecurityLevel::Moderate < SecurityLevel::Elevated);
        assert!(SecurityLevel::Elevated < SecurityLevel::Critical);
    }

    #[test]
    fn test_init_creates_all_automations() {
        let state = init();
        // Phase 1 Stabilisation: Gérer lock poison
        let configs = match state.configs.lock() {
            Ok(c) => c,
            Err(e) => {
                eprintln!("Warning: Automations configs lock poisoned, recovering: {}", e);
                e.into_inner()
            }
        };
        assert_eq!(configs.len(), 16);
    }

    #[test]
    fn test_validation_permission() {
        let config = AutomationConfig {
            id: "test".to_string(),
            name: "Test".to_string(),
            category: AutomationCategory::System,
            security_level: SecurityLevel::Moderate,
            required_permission: 3,
            allowed_modes: None,
            base_xp_reward: 10,
            requires_confirmation: false,
            timeout_ms: 1000,
            cooldown_ms: 0,
        };

        let request = AutomationRequest {
            automation_id: "test".to_string(),
            parameters: HashMap::new(),
            mode_id: "default".to_string(),
            permission_level: 2,
            triggered_by: "user".to_string(),
            user_confirmed: false,
        };

        let result = validate_automation_request(&config, &request, &HashMap::new(), &HashSet::new());
        assert!(result.is_err());
        assert!(result.unwrap_err().contains("Permission insuffisante"));
    }

    #[test]
    fn test_validation_mode_restriction() {
        let config = AutomationConfig {
            id: "test".to_string(),
            name: "Test".to_string(),
            category: AutomationCategory::System,
            security_level: SecurityLevel::Safe,
            required_permission: 0,
            allowed_modes: Some(vec!["dev".to_string()]),
            base_xp_reward: 10,
            requires_confirmation: false,
            timeout_ms: 1000,
            cooldown_ms: 0,
        };

        let request = AutomationRequest {
            automation_id: "test".to_string(),
            parameters: HashMap::new(),
            mode_id: "default".to_string(),
            permission_level: 5,
            triggered_by: "user".to_string(),
            user_confirmed: false,
        };

        let result = validate_automation_request(&config, &request, &HashMap::new(), &HashSet::new());
        assert!(result.is_err());
        assert!(result.unwrap_err().contains("non autorisé"));
    }
}
