#!/usr/bin/env bash
# ═══════════════════════════════════════════════════════════════
#   TITANE∞ Remote Access — Configure Cloudflare Tunnel
#   Creates a named tunnel pointing to localhost:7420.
#   Prerequisites: cloudflared installed + Cloudflare account logged in
#   Run: cloudflared login (once)  →  then this script
# ═══════════════════════════════════════════════════════════════
set -euo pipefail

TUNNEL_NAME="${TITANE_TUNNEL_NAME:-titane-remote}"
LOCAL_PORT="${TITANE_REMOTE_PORT:-7420}"
CONFIG_DIR="${HOME}/.cloudflared"
CONFIG_FILE="${CONFIG_DIR}/titane-tunnel.yml"
CREDENTIALS_DIR="${HOME}/.titane/tunnel"

check_cloudflared() {
    if ! command -v cloudflared &>/dev/null; then
        echo "[setup-tunnel] ❌ cloudflared not found. Run: bash scripts/remote/install-cloudflare-tunnel.sh"
        exit 1
    fi
}

check_logged_in() {
    if [[ ! -f "${CONFIG_DIR}/cert.pem" ]]; then
        echo "[setup-tunnel] ⚠️  Cloudflare not logged in."
        echo "               Run: cloudflared login"
        echo "               Then re-run this script."
        exit 1
    fi
}

create_tunnel() {
    echo "[setup-tunnel] Creating tunnel '${TUNNEL_NAME}'..."
    mkdir -p "$CREDENTIALS_DIR"

    # Check if already exists
    if cloudflared tunnel list 2>/dev/null | grep -q "$TUNNEL_NAME"; then
        echo "[setup-tunnel] ℹ️  Tunnel '${TUNNEL_NAME}' already exists — reusing"
    else
        cloudflared tunnel create "$TUNNEL_NAME"
        echo "[setup-tunnel] ✅ Tunnel '${TUNNEL_NAME}' created"
    fi

    # Get tunnel ID
    TUNNEL_ID=$(cloudflared tunnel list --output json 2>/dev/null \
        | python3 -c "import sys,json; [print(t['id']) for t in json.load(sys.stdin) if t['name']=='${TUNNEL_NAME}']" \
        || echo "")

    if [[ -z "$TUNNEL_ID" ]]; then
        echo "[setup-tunnel] ❌ Could not determine tunnel ID"
        exit 1
    fi

    echo "[setup-tunnel] Tunnel ID: ${TUNNEL_ID}"

    # Write config file
    mkdir -p "$CONFIG_DIR"
    cat > "$CONFIG_FILE" <<EOF
# TITANE∞ Cloudflare Tunnel — auto-generated by setup-tunnel.sh
# Edit TITANE_TUNNEL_NAME and TITANE_REMOTE_PORT env vars to customize.

tunnel: ${TUNNEL_ID}
credentials-file: ${HOME}/.cloudflared/${TUNNEL_ID}.json

ingress:
  - service: http://127.0.0.1:${LOCAL_PORT}

EOF

    echo "[setup-tunnel] ✅ Config written to: ${CONFIG_FILE}"
    echo ""
    echo "══════════════════════════════════════════════════════════"
    echo "  TITANE Remote Access — Tunnel configured!"
    echo ""
    echo "  Tunnel: ${TUNNEL_NAME} (ID: ${TUNNEL_ID})"
    echo "  Target: http://127.0.0.1:${LOCAL_PORT}"
    echo ""
    echo "  To route a custom domain (optional):"
    echo "    cloudflared tunnel route dns ${TUNNEL_NAME} titane.yourdomain.com"
    echo ""
    echo "  To start the tunnel:"
    echo "    bash scripts/remote/start-tunnel.sh"
    echo "══════════════════════════════════════════════════════════"
}

main() {
    check_cloudflared
    check_logged_in
    create_tunnel
}

main "$@"
