/**
 * TITANE∞ v∞ Phase 8 - Mode Création (Super-Prompt S)
 * Auto-Generation Engine - Modules/UI/Tools
 */
use serde::{Deserialize, Serialize};
use std::collections::HashMap;

// ══════════════════════════════════════════════════════════════════
// TYPES
// ══════════════════════════════════════════════════════════════════

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CreationRequest {
    pub id: String,
    pub intent: String,
    pub target_type: TargetType,
    pub parameters: HashMap<String, String>,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq, Hash)]
pub enum TargetType {
    RustModule,
    TypeScriptComponent,
    ReactPage,
    TauriCommand,
    UIWidget,
    DataModel,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct GeneratedArtifact {
    pub id: String,
    pub name: String,
    pub target_type: TargetType,
    pub code: String,
    pub dependencies: Vec<String>,
    pub tests: Option<String>,
    pub documentation: String,
}

// ══════════════════════════════════════════════════════════════════
// CREATION ENGINE
// ══════════════════════════════════════════════════════════════════

pub struct CreationEngine {
    templates: HashMap<TargetType, String>,
}

impl CreationEngine {
    pub fn new() -> Self {
        let mut engine = Self {
            templates: HashMap::new(),
        };
        engine.load_templates();
        engine
    }

    fn load_templates(&mut self) {
        // Rust module template
        self.templates.insert(
            TargetType::RustModule,
            r#"
// Auto-generated by TITANE∞ Creation Engine
use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct {{NAME}} {
    pub id: String,
    {{FIELDS}}
}

impl {{NAME}} {
    pub fn new({{PARAMS}}) -> Self {
        Self {
            id: uuid::Uuid::new_v4().to_string(),
            {{INIT}}
        }
    }

    {{METHODS}}
}
"#
            .to_string(),
        );

        // TypeScript component template
        self.templates.insert(
            TargetType::TypeScriptComponent,
            r#"
/**
 * Auto-generated by TITANE∞ Creation Engine
 * Component: {{NAME}}
 */
import React from 'react';

interface {{NAME}}Props {
    {{PROPS}}
}

export const {{NAME}}: React.FC<{{NAME}}Props> = ({{PROP_NAMES}}) => {
    {{STATE}}

    return (
        <div className="{{CLASS_NAME}}">
            {{CONTENT}}
        </div>
    );
};
"#
            .to_string(),
        );

        // React page template
        self.templates.insert(
            TargetType::ReactPage,
            r#"
/**
 * Auto-generated by TITANE∞ Creation Engine
 * Page: {{NAME}}
 */
import React from 'react';

export const {{NAME}}: React.FC = () => {
    return (
        <main className="{{CLASS_NAME}}">
            {{CONTENT}}
        </main>
    );
};
"#
            .to_string(),
        );
    }

    /// Analyze intent and generate code
    pub async fn create_from_intent(
        &self,
        request: CreationRequest,
    ) -> Result<GeneratedArtifact, String> {
        let template = self
            .templates
            .get(&request.target_type)
            .ok_or("Template not found")?;

        // Simple template substitution (in production, use AI-powered generation)
        let mut code = template.clone();

        for (key, value) in &request.parameters {
            let placeholder = format!("{{{{{}}}}}", key);
            code = code.replace(&placeholder, value);
        }

        let dependencies = self.infer_dependencies(&code);
        let tests = self.generate_tests(&code);
        let documentation = self.generate_docs(&request.intent);

        Ok(GeneratedArtifact {
            id: request.id.clone(),
            name: request
                .parameters
                .get("NAME")
                .unwrap_or(&"Generated".to_string())
                .clone(),
            target_type: request.target_type,
            code,
            dependencies,
            tests: Some(tests),
            documentation,
        })
    }

    fn infer_dependencies(&self, code: &str) -> Vec<String> {
        let mut deps = Vec::new();

        if code.contains("use serde") {
            deps.push("serde = { version = \"1.0\", features = [\"derive\"] }".to_string());
        }
        if code.contains("uuid::Uuid") {
            deps.push("uuid = { version = \"1.0\", features = [\"v4\"] }".to_string());
        }
        if code.contains("tokio::") {
            deps.push("tokio = { version = \"1.0\", features = [\"full\"] }".to_string());
        }

        deps
    }

    fn generate_tests(&self, _code: &str) -> String {
        "#[cfg(test)]\nmod tests {\n    use super::*;\n    \n    #[test]\n    fn test_creation() {\n        // TODO: Add tests\n    }\n}".to_string()
    }

    fn generate_docs(&self, intent: &str) -> String {
        format!(
            "# Generated Module\n\nIntent: {}\n\nGenerated by TITANE∞ Creation Engine v∞",
            intent
        )
    }
}

impl Default for CreationEngine {
    fn default() -> Self {
        Self::new()
    }
}

// ══════════════════════════════════════════════════════════════════
// TAURI COMMANDS
// ══════════════════════════════════════════════════════════════════

#[tauri::command]
pub async fn create_module(
    intent: String,
    target_type: String,
) -> Result<GeneratedArtifact, String> {
    let engine = CreationEngine::new();

    let target = match target_type.as_str() {
        "rust" => TargetType::RustModule,
        "typescript" => TargetType::TypeScriptComponent,
        "react" => TargetType::ReactPage,
        _ => return Err("Unknown target type".to_string()),
    };

    let request = CreationRequest {
        id: uuid::Uuid::new_v4().to_string(),
        intent: intent.clone(),
        target_type: target,
        parameters: {
            let mut params = HashMap::new();
            params.insert("NAME".to_string(), "GeneratedModule".to_string());
            params.insert("FIELDS".to_string(), "data: String,".to_string());
            params
        },
    };

    engine.create_from_intent(request).await
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_creation_engine_new() {
        let engine = CreationEngine::new();
        assert!(!engine.templates.is_empty());
    }

    #[test]
    fn test_creation_engine_default() {
        let engine = CreationEngine::default();
        assert!(!engine.templates.is_empty());
    }

    #[test]
    fn test_target_type_variants() {
        let types = vec![
            TargetType::RustModule,
            TargetType::TypeScriptComponent,
            TargetType::ReactPage,
            TargetType::TauriCommand,
            TargetType::UIWidget,
            TargetType::DataModel,
        ];

        for t in types {
            // Ensure all variants are hashable and cloneable
            let cloned = t.clone();
            assert_eq!(t, cloned);
        }
    }

    #[test]
    fn test_creation_request_structure() {
        let mut params = HashMap::new();
        params.insert("NAME".to_string(), "TestModule".to_string());

        let request = CreationRequest {
            id: "test-123".to_string(),
            intent: "Create a test module".to_string(),
            target_type: TargetType::RustModule,
            parameters: params,
        };

        assert_eq!(request.id, "test-123");
        assert_eq!(request.intent, "Create a test module");
        assert_eq!(request.target_type, TargetType::RustModule);
        assert!(request.parameters.contains_key("NAME"));
    }

    #[test]
    fn test_generated_artifact_structure() {
        let artifact = GeneratedArtifact {
            id: "artifact-1".to_string(),
            name: "TestArtifact".to_string(),
            target_type: TargetType::TypeScriptComponent,
            code: "const x = 1;".to_string(),
            dependencies: vec!["react".to_string()],
            tests: Some("test code".to_string()),
            documentation: "docs".to_string(),
        };

        assert_eq!(artifact.id, "artifact-1");
        assert_eq!(artifact.name, "TestArtifact");
        assert_eq!(artifact.dependencies.len(), 1);
        assert!(artifact.tests.is_some());
    }

    #[test]
    fn test_infer_dependencies_serde() {
        let engine = CreationEngine::new();
        let code = "use serde::{Deserialize, Serialize};";

        let deps = engine.infer_dependencies(code);
        assert!(deps.iter().any(|d| d.contains("serde")));
    }

    #[test]
    fn test_infer_dependencies_uuid() {
        let engine = CreationEngine::new();
        let code = "let id = uuid::Uuid::new_v4();";

        let deps = engine.infer_dependencies(code);
        assert!(deps.iter().any(|d| d.contains("uuid")));
    }

    #[test]
    fn test_infer_dependencies_tokio() {
        let engine = CreationEngine::new();
        let code = "tokio::spawn(async {});";

        let deps = engine.infer_dependencies(code);
        assert!(deps.iter().any(|d| d.contains("tokio")));
    }

    #[test]
    fn test_infer_dependencies_none() {
        let engine = CreationEngine::new();
        let code = "fn main() {}";

        let deps = engine.infer_dependencies(code);
        assert!(deps.is_empty());
    }

    #[test]
    fn test_generate_tests() {
        let engine = CreationEngine::new();
        let tests = engine.generate_tests("any code");

        assert!(tests.contains("#[cfg(test)]"));
        assert!(tests.contains("mod tests"));
        assert!(tests.contains("#[test]"));
    }

    #[test]
    fn test_generate_docs() {
        let engine = CreationEngine::new();
        let docs = engine.generate_docs("Create a user module");

        assert!(docs.contains("Create a user module"));
        assert!(docs.contains("TITANE∞"));
    }

    #[test]
    fn test_templates_contain_rust_module() {
        let engine = CreationEngine::new();
        assert!(engine.templates.contains_key(&TargetType::RustModule));
    }

    #[test]
    fn test_templates_contain_typescript() {
        let engine = CreationEngine::new();
        assert!(engine.templates.contains_key(&TargetType::TypeScriptComponent));
    }

    #[tokio::test]
    async fn test_create_from_intent_rust() {
        let engine = CreationEngine::new();

        let mut params = HashMap::new();
        params.insert("NAME".to_string(), "MyModule".to_string());
        params.insert("FIELDS".to_string(), "value: i32,".to_string());
        params.insert("PARAMS".to_string(), "value: i32".to_string());
        params.insert("INIT".to_string(), "value".to_string());
        params.insert("METHODS".to_string(), "".to_string());

        let request = CreationRequest {
            id: "req-1".to_string(),
            intent: "Create MyModule".to_string(),
            target_type: TargetType::RustModule,
            parameters: params,
        };

        let result = engine.create_from_intent(request).await;
        assert!(result.is_ok());

        let artifact = result.unwrap();
        assert_eq!(artifact.name, "MyModule");
        assert!(artifact.code.contains("MyModule"));
    }

    #[tokio::test]
    async fn test_create_from_intent_typescript() {
        let engine = CreationEngine::new();

        let mut params = HashMap::new();
        params.insert("NAME".to_string(), "MyComponent".to_string());
        params.insert("PROPS".to_string(), "title: string;".to_string());
        params.insert("PROP_NAMES".to_string(), "{ title }".to_string());
        params.insert("STATE".to_string(), "".to_string());
        params.insert("CLASS_NAME".to_string(), "my-component".to_string());
        params.insert("CONTENT".to_string(), "{title}".to_string());

        let request = CreationRequest {
            id: "req-2".to_string(),
            intent: "Create React component".to_string(),
            target_type: TargetType::TypeScriptComponent,
            parameters: params,
        };

        let result = engine.create_from_intent(request).await;
        assert!(result.is_ok());

        let artifact = result.unwrap();
        assert!(artifact.code.contains("React"));
        assert!(artifact.code.contains("MyComponent"));
    }

    #[tokio::test]
    async fn test_create_from_intent_missing_template() {
        let engine = CreationEngine::new();

        let request = CreationRequest {
            id: "req-3".to_string(),
            intent: "Create widget".to_string(),
            target_type: TargetType::UIWidget, // No template defined
            parameters: HashMap::new(),
        };

        let result = engine.create_from_intent(request).await;
        assert!(result.is_err());
        assert!(result.unwrap_err().contains("Template not found"));
    }

    #[test]
    fn test_artifact_clone() {
        let artifact = GeneratedArtifact {
            id: "id".to_string(),
            name: "name".to_string(),
            target_type: TargetType::DataModel,
            code: "code".to_string(),
            dependencies: vec!["dep".to_string()],
            tests: None,
            documentation: "doc".to_string(),
        };

        let cloned = artifact.clone();
        assert_eq!(cloned.id, artifact.id);
        assert_eq!(cloned.name, artifact.name);
    }

    #[test]
    fn test_artifact_debug() {
        let artifact = GeneratedArtifact {
            id: "debug-test".to_string(),
            name: "DebugArtifact".to_string(),
            target_type: TargetType::RustModule,
            code: "fn main() {}".to_string(),
            dependencies: vec![],
            tests: None,
            documentation: "".to_string(),
        };
        let debug_str = format!("{:?}", artifact);
        assert!(debug_str.contains("GeneratedArtifact"));
    }

    #[test]
    fn test_creation_request_debug() {
        let request = CreationRequest {
            id: "req-debug".to_string(),
            intent: "Debug test".to_string(),
            target_type: TargetType::ReactPage,
            parameters: HashMap::new(),
        };
        let debug_str = format!("{:?}", request);
        assert!(debug_str.contains("CreationRequest"));
    }

    #[test]
    fn test_creation_request_clone() {
        let mut params = HashMap::new();
        params.insert("KEY".to_string(), "VALUE".to_string());

        let request = CreationRequest {
            id: "clone-test".to_string(),
            intent: "Test clone".to_string(),
            target_type: TargetType::TauriCommand,
            parameters: params,
        };

        let cloned = request.clone();
        assert_eq!(cloned.id, request.id);
        assert_eq!(cloned.parameters.get("KEY"), request.parameters.get("KEY"));
    }

    #[test]
    fn test_target_type_debug() {
        let target = TargetType::UIWidget;
        let debug_str = format!("{:?}", target);
        assert!(debug_str.contains("UIWidget"));
    }

    #[test]
    fn test_target_type_serialization() {
        let target = TargetType::RustModule;
        let json = serde_json::to_string(&target).unwrap();
        let restored: TargetType = serde_json::from_str(&json).unwrap();
        assert_eq!(restored, target);
    }

    #[test]
    fn test_all_target_types_serialization() {
        let types = vec![
            TargetType::RustModule,
            TargetType::TypeScriptComponent,
            TargetType::ReactPage,
            TargetType::TauriCommand,
            TargetType::UIWidget,
            TargetType::DataModel,
        ];

        for t in types {
            let json = serde_json::to_string(&t).unwrap();
            let restored: TargetType = serde_json::from_str(&json).unwrap();
            assert_eq!(restored, t);
        }
    }

    #[test]
    fn test_infer_dependencies_multiple() {
        let engine = CreationEngine::new();
        let code = "use serde::{Deserialize, Serialize};\nlet id = uuid::Uuid::new_v4();\ntokio::spawn(async {});";

        let deps = engine.infer_dependencies(code);
        assert_eq!(deps.len(), 3);
        assert!(deps.iter().any(|d| d.contains("serde")));
        assert!(deps.iter().any(|d| d.contains("uuid")));
        assert!(deps.iter().any(|d| d.contains("tokio")));
    }

    #[test]
    fn test_generate_docs_format() {
        let engine = CreationEngine::new();
        let docs = engine.generate_docs("Create a user authentication module");

        assert!(docs.contains("Create a user authentication module"));
        assert!(docs.contains("TITANE"));
        assert!(docs.contains("Generated"));
    }

    #[test]
    fn test_generate_tests_structure() {
        let engine = CreationEngine::new();
        let tests = engine.generate_tests("sample code");

        assert!(tests.contains("#[cfg(test)]"));
        assert!(tests.contains("mod tests"));
        assert!(tests.contains("use super::*"));
        assert!(tests.contains("fn test_creation"));
    }

    #[test]
    fn test_creation_engine_templates_initialized() {
        let engine = CreationEngine::new();
        // At least 2 templates should be loaded
        assert!(engine.templates.len() >= 2);
    }

    #[test]
    fn test_rust_template_contains_markers() {
        let engine = CreationEngine::new();
        let template = engine.templates.get(&TargetType::RustModule).unwrap();

        assert!(template.contains("{{NAME}}"));
        assert!(template.contains("{{FIELDS}}"));
        assert!(template.contains("{{PARAMS}}"));
    }

    #[test]
    fn test_typescript_template_contains_markers() {
        let engine = CreationEngine::new();
        let template = engine.templates.get(&TargetType::TypeScriptComponent).unwrap();

        assert!(template.contains("{{NAME}}"));
        assert!(template.contains("{{PROPS}}"));
        assert!(template.contains("React"));
    }

    #[tokio::test]
    async fn test_create_from_intent_default_name() {
        let engine = CreationEngine::new();

        let request = CreationRequest {
            id: "default-name-test".to_string(),
            intent: "Test default naming".to_string(),
            target_type: TargetType::RustModule,
            parameters: HashMap::new(), // No NAME parameter
        };

        let result = engine.create_from_intent(request).await;
        assert!(result.is_ok());

        let artifact = result.unwrap();
        assert_eq!(artifact.name, "Generated");
    }

    #[test]
    fn test_artifact_with_tests_some() {
        let artifact = GeneratedArtifact {
            id: "with-tests".to_string(),
            name: "TestModule".to_string(),
            target_type: TargetType::RustModule,
            code: "code".to_string(),
            dependencies: vec![],
            tests: Some("test code".to_string()),
            documentation: "docs".to_string(),
        };

        assert!(artifact.tests.is_some());
        assert_eq!(artifact.tests.unwrap(), "test code");
    }

    #[test]
    fn test_artifact_with_tests_none() {
        let artifact = GeneratedArtifact {
            id: "no-tests".to_string(),
            name: "NoTestModule".to_string(),
            target_type: TargetType::DataModel,
            code: "code".to_string(),
            dependencies: vec![],
            tests: None,
            documentation: "docs".to_string(),
        };

        assert!(artifact.tests.is_none());
    }

    #[test]
    fn test_request_serialization_roundtrip() {
        let mut params = HashMap::new();
        params.insert("NAME".to_string(), "TestModule".to_string());

        let request = CreationRequest {
            id: "serial-test".to_string(),
            intent: "Test serialization".to_string(),
            target_type: TargetType::TypeScriptComponent,
            parameters: params,
        };

        let json = serde_json::to_string(&request).unwrap();
        let restored: CreationRequest = serde_json::from_str(&json).unwrap();

        assert_eq!(restored.id, request.id);
        assert_eq!(restored.intent, request.intent);
    }

    #[test]
    fn test_artifact_serialization_roundtrip() {
        let artifact = GeneratedArtifact {
            id: "serial-artifact".to_string(),
            name: "SerialModule".to_string(),
            target_type: TargetType::ReactPage,
            code: "export default function Page() {}".to_string(),
            dependencies: vec!["react".to_string(), "next".to_string()],
            tests: Some("test".to_string()),
            documentation: "Page component".to_string(),
        };

        let json = serde_json::to_string(&artifact).unwrap();
        let restored: GeneratedArtifact = serde_json::from_str(&json).unwrap();

        assert_eq!(restored.id, artifact.id);
        assert_eq!(restored.dependencies.len(), 2);
    }

    #[test]
    fn test_target_type_hash() {
        use std::collections::HashSet;

        let mut set = HashSet::new();
        set.insert(TargetType::RustModule);
        set.insert(TargetType::TypeScriptComponent);
        set.insert(TargetType::RustModule); // Duplicate

        assert_eq!(set.len(), 2);
    }

    #[test]
    fn test_empty_parameters_handling() {
        let engine = CreationEngine::new();
        let template = engine.templates.get(&TargetType::RustModule).unwrap();

        // Template with no substitutions should remain with placeholders
        let code = template.clone();
        assert!(code.contains("{{"));
    }

    #[tokio::test]
    async fn test_create_module_tauri_command_rust() {
        let result = create_module("Test intent".to_string(), "rust".to_string()).await;
        assert!(result.is_ok());

        let artifact = result.unwrap();
        assert_eq!(artifact.target_type, TargetType::RustModule);
    }

    #[tokio::test]
    async fn test_create_module_tauri_command_typescript() {
        let result = create_module("Create component".to_string(), "typescript".to_string()).await;
        assert!(result.is_ok());

        let artifact = result.unwrap();
        assert_eq!(artifact.target_type, TargetType::TypeScriptComponent);
    }

    #[tokio::test]
    async fn test_create_module_tauri_command_react() {
        let result = create_module("Create page".to_string(), "react".to_string()).await;
        assert!(result.is_ok());

        let artifact = result.unwrap();
        assert_eq!(artifact.target_type, TargetType::ReactPage);
    }

    #[tokio::test]
    async fn test_create_module_tauri_command_unknown() {
        let result = create_module("Test".to_string(), "unknown_type".to_string()).await;
        assert!(result.is_err());
        assert!(result.unwrap_err().contains("Unknown target type"));
    }
}
