#!/usr/bin/env bash
# checks/check_G1_BUILD_TAURI_X3.sh — Gate G1: Tauri build reproducible x3
# Ring: 4 — Status: STABLE
# Rollback: git restore -- checks/check_G1_BUILD_TAURI_X3.sh
# NOTE: Actual build execution must happen in VS Code (Tauri + Rust toolchain required).

set -euo pipefail
GATE="G1_BUILD_TAURI_X3"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=./_lib.sh
source "${SCRIPT_DIR}/_lib.sh"

ROOT="$(lib_repo_root)"
PACK_DIR="${PROOF_PACKS_DIR}/${GATE}"
mkdir -p "$PACK_DIR"

# Check for pre-existing x3 proof files (generated by VS Code after merge)
X3_RESULTS=("${PACK_DIR}/build_run1.jsonl" "${PACK_DIR}/build_run2.jsonl" "${PACK_DIR}/build_run3.jsonl")
FOUND=0
for f in "${X3_RESULTS[@]}"; do
  [[ -f "$f" ]] && FOUND=$((FOUND+1))
done

if [[ $FOUND -ge 3 ]]; then
  lib_pass "$GATE" "x3 build proof files present (runs: $FOUND)"
  exit 0
fi

# Tauri toolchain not available in this environment — emit BLOCKED_RUNNER
lib_blocked_runner "$GATE" \
  "Tauri/Rust toolchain not available in CI prep environment" \
  "Run 'pnpm run build:tauri' x3 in VS Code after merge; store results in ${PACK_DIR}/build_runN.jsonl"

lib_log "INFO" "[$GATE] Prerequisite check: src-tauri/Cargo.toml"
lib_require_file "$GATE" "${ROOT}/src-tauri/Cargo.toml" || true
lib_log "INFO" "[$GATE] Prerequisite check: src-tauri/tauri.conf.json"
lib_require_file "$GATE" "${ROOT}/src-tauri/tauri.conf.json" || true

exit 0
