export const uiPages = {
  titane: {
    id: 'titane',
    route: '/titane',
    navTestId: 'nav-titane',
    root: '[data-testid="page-titane"]',
    tabs: [
      '[data-testid="tab-conversation"]',
      '[data-testid="tab-overview"]',
      '[data-testid="tab-vision"]',
      '[data-testid="tab-identity"]',
      '[data-testid="tab-memory"]',
      '[data-testid="tab-memory-evolution"]',
      '[data-testid="tab-progression"]',
      '[data-testid="tab-transformation"]',
    ],
  },
  time: {
    id: 'time',
    route: '/time',
    navTestId: 'nav-time',
    root: '[data-testid="page-time"]',
    tabs: [
      '[data-testid="tab-time-now"]',
      '[data-testid="tab-time-agenda"]',
      '[data-testid="tab-time-timeline"]',
      '[data-testid="tab-time-snapshots"]',
      '[data-testid="tab-time-cognitive"]',
    ],
  },
  stats: {
    id: 'stats',
    route: '/dev',
    navTestId: 'nav-dev',
    root: '[data-testid="page-dev"]',
    tabs: [],
  },
  admin: {
    id: 'admin',
    route: '/admin',
    navTestId: 'nav-admin',
    root: '[data-testid="page-admin"]',
    tabs: [
      '[data-testid="tab-admin-system"]',
      '[data-testid="tab-admin-config"]',
      '[data-testid="tab-admin-audio"]',
      '[data-testid="tab-admin-design"]',
      '[data-testid="tab-admin-governance"]',
      '[data-testid="tab-admin-production-health"]',
    ],
  },
  dev: {
    id: 'dev',
    route: '/dev',
    navTestId: 'nav-dev',
    root: '[data-testid="page-dev"]',
    tabs: [
      '[data-testid="tab-dev-overview"]',
      '[data-testid="tab-dev-diagnostics"]',
      '[data-testid="tab-dev-operations"]',
      '[data-testid="tab-dev-validation"]',
      '[data-testid="tab-dev-security"]',
    ],
  },
  fusion: {
    id: 'fusion',
    route: '/fusion',
    navTestId: 'nav-fusion',
    root: '[data-testid="page-fusion"]',
    tabs: [],
  },
  optimization: {
    id: 'optimization',
    route: '/optimization',
    navTestId: 'nav-optimization',
    root: '[data-testid="page-optimization"]',
    tabs: [],
  },
};

export const topLevelPageOrder = [
  uiPages.titane,
  uiPages.time,
  uiPages.admin,
  uiPages.dev,
  uiPages.fusion,
  uiPages.optimization,
];
